### ISSUE TITLE
What is this doing exactly?

### ISSUE THREAD

**Issue by eabase** [JafferWilson/MT4-Ticks-To-MT5#3]
@JafferWilson 
If this is doing what I think, it is really cool! So plaase clarify. 

I can connect my MT4 to my broker, but run my MT5 without a broker connection, and still get the tick charts from the MT4?

**Comment by JafferWilson** [comment]
It is broker independent in MT5. But it can be risky. As there might be confusion in the brokers. But if you have a broker in MT4 and MT5 is demo version, then you will receive the MT4 broker ticks in MT5.
I hope it is clear.

**Comment by JafferWilson** [comment]
I am closing this issue as it is not at all an issue.

**Comment by eabase** [comment]
@JafferWilson 
I don't have those symbols in the text files. 
my symbols are "dotted" like `EURUSD.x` and so on. 
Do I need to edit that file or how can I find the correct codes for my symbols?

**Comment by JafferWilson** [comment]
In MT5, it is created automatically. You need not have to edit anything.
