### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by eabase** [JafferWilson/MT4-Ticks-To-MT5#6]
- [x] Q: *Can we also pump data in the reverse direction?*  
(I.e. using MT5 as tick source and push to be shown in MT4, by switching the EA's.)

- [x] Q: *I would like to use a different tick-data source to push ticks to MT5 (or MT4 if allowed by above), can this be done?*  
 (What is the format needed to be sent to the socket?)  
  
  **A**: Seem to be something like this:  
  https://github.com/JafferWilson/MT4-Ticks-To-MT5/blob/8934a7148dbc5d090aa4f61ca2d5a019fc0a7fe0/MT4.mq4#L68-L78  

```mql4
_Symbol,
long(TimeCurrent()),
Ask,
Bid,
long(TimeCurrent()), 
long(Time[0]),
Open[0],
High[0],
Low[0],
Close[0],
int(fabs(Ask-Bid)/Point),
Volume[0])
```
<sub>Why is `TimeCurrent()` used twice?</sub>

- [x] Q: *What is the intended purpose and function of the CSV files?*

    1. Do they store the tick or candle data?
      **A**: Yes. .hst is the history files for MT4 symbols.
    
    2. Are they used to reload old data when starting up?
      **A**: Yes. Any symbol needs history. Otherwise, they will start with candle 0 and you might have to wait for the candles to get filled in your chart before your try some analysis.

- [x] Q: *Are the CSV files created and stored in both MT4 and MT5 sides?*
     **A**:  No. Only MT4. For the history purpose.

**Comment by JafferWilson** [comment]
The actual reason behind using TimeCurrent() 2 times lies in the usage of the program.
I was using the same program (obviously after little modification) in MT5 to MT5 tick transfer. As there where two brokers ticks I was using for analysis. Hence, I have not changed the pattern as the same program could be used from MT4 to MT5 or MT5 to MT5. 
Hence, it is just a pattern. If you do not want it, feel free to modify your way.

**Comment by JafferWilson** [comment]
Regarding the reverse direction, the answer is Yes.
It is very much possible.
You just need to understand the programming a bit and you can do it. It is just a simple socket communication program.
If you want to used it in reverse direction then just understand the formats of MT5 and MT4. 
Anything can be done.
I hope this answers all your queries. Please close this issue if satisfied.
